// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transaction

import (
	"context"

	"github.com/leandrodam/transactions/internal/domain/transaction"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Create(ctx context.Context, transaction1 transaction.Transaction) (transaction.Transaction, error) {
	ret := _mock.Called(ctx, transaction1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 transaction.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Transaction) (transaction.Transaction, error)); ok {
		return returnFunc(ctx, transaction1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Transaction) transaction.Transaction); ok {
		r0 = returnFunc(ctx, transaction1)
	} else {
		r0 = ret.Get(0).(transaction.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, transaction.Transaction) error); ok {
		r1 = returnFunc(ctx, transaction1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction1 transaction.Transaction
func (_e *MockUseCase_Expecter) Create(ctx interface{}, transaction1 interface{}) *MockUseCase_Create_Call {
	return &MockUseCase_Create_Call{Call: _e.mock.On("Create", ctx, transaction1)}
}

func (_c *MockUseCase_Create_Call) Run(run func(ctx context.Context, transaction1 transaction.Transaction)) *MockUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 transaction.Transaction
		if args[1] != nil {
			arg1 = args[1].(transaction.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_Create_Call) Return(transaction11 transaction.Transaction, err error) *MockUseCase_Create_Call {
	_c.Call.Return(transaction11, err)
	return _c
}

func (_c *MockUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, transaction1 transaction.Transaction) (transaction.Transaction, error)) *MockUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}
