// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transactor

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTransactor
func (_mock *MockTransactor) WithinTransaction(context1 context.Context, fn func(context.Context) error) error {
	ret := _mock.Called(context1, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(context1, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTransactor_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - context1 context.Context
//   - fn func(context.Context) error
func (_e *MockTransactor_Expecter) WithinTransaction(context1 interface{}, fn interface{}) *MockTransactor_WithinTransaction_Call {
	return &MockTransactor_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", context1, fn)}
}

func (_c *MockTransactor_WithinTransaction_Call) Run(run func(context1 context.Context, fn func(context.Context) error)) *MockTransactor_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactor_WithinTransaction_Call) Return(err error) *MockTransactor_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_WithinTransaction_Call) RunAndReturn(run func(context1 context.Context, fn func(context.Context) error) error) *MockTransactor_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}
